tags:
- name: Account
  description: Bitcoin Account API

paths:
  /product:
    post:
      tags:
      - Accounts
      summary: Create an Account
      parameters:
      - name: body
        in: body
        description: Account Data
        required: true
        schema:
          $ref: '#/definitions/account'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'
  /account/balance/{_id}:
    get:
      tags:
      - Account
      summary: Get account balance by account id
      parameters:
      - name: _id
        in: path
        description: Account id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  /account/sweep/{_id}:
    get:
      tags:
      - Account
      summary: Sweep bitcoin account by accountId
      parameters:
      - name: _id
        in: path
        description: Account id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  account:
    type: object
    required:
        - name
    properties:
      name:
        type: string
        description: User Name
   
schemes:
 - http